# Generated by Django 5.1.3 on 2025-02-21 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='email',
            new_name='user_email',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='name',
            new_name='user_name',
        ),
    ]
